# frozen_string_literal: true

source 'https://rubygems.org'

group :development, :test do
  gem 'bps', path: './bps'
  gem 'bps-kafka', path: './bps-kafka'

  gem 'rake'
  gem 'rspec'
  gem 'rubocop'
end
