# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'rubocop', '~> 0.84.0', group: :development

gem 'rake', '~> 13.0', group: :development
