inherit_from:
  - https://gitlab.com/bsm/misc/raw/master/rubocop/default.yml

AllCops:
  TargetRubyVersion: "2.6"
Metrics/ParameterLists:
  Max: 8
Metrics/MethodLength:
  Exclude:
    - "ruby/bps/lib/bps/coercer.rb"
Naming/FileName:
  Exclude:
    - "ruby/bps-kafka/lib/bps-kafka.rb"
    - "ruby/bps-stan/lib/bps-stan.rb"
