inherit_gem:
  rubocop-bsm:
    - default.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: "2.6"

Naming/FileName:
  Exclude:
    - "ruby/bps-kafka/lib/bps-kafka.rb"
    - "ruby/bps-nats/lib/bps-nats.rb"
    - "ruby/bps-stan/lib/bps-stan.rb"
