matrix:
  include:
    - language: go
      go:
        - 1.13.x
      services:
        - docker
      install:
        - docker --version
        - docker-compose --version
        - go get honnef.co/go/tools/cmd/staticcheck
      before_script:
        - docker-compose -f testdata/docker-compose.yml up -d
      script:
        - make default staticcheck
      cache:
        directories:
          - $GOPATH/pkg/mod
    - language: go
      go:
        - 1.14.x
      services:
        - docker
      install:
        - docker --version
        - docker-compose --version
        - go get honnef.co/go/tools/cmd/staticcheck
      before_script:
        - docker-compose -f testdata/docker-compose.yml up -d
      script:
        - make default staticcheck
      cache:
        directories:
          - $GOPATH/pkg/mod
    - language: ruby
      ruby:
        - 2.6
      env:
        - KAFKA_ADDRS=:9092
      services:
        - docker
      install:
        - docker --version
        - docker-compose --version
        - gem install bundler
      before_script:
        - docker-compose -f testdata/docker-compose.yml up -d
        - cd ruby
        - bundle install --jobs=3 --retry=3
      script:
        - bundle exec rake
      cache: bundler
    - language: ruby
      ruby:
        - 2.7
      env:
        - KAFKA_ADDRS=:9092
      services:
        - docker
      install:
        - docker --version
        - docker-compose --version
        - gem install bundler
      before_script:
        - docker-compose -f testdata/docker-compose.yml up -d
        - cd ruby
        - bundle install --jobs=3 --retry=3
      script:
        - bundle exec rake
      cache: bundler
